CREATE TABLE cloth(
    part varchar2(100),
    brand varchar2(100),
    price number
);

ALTER TABLE cloth RENAME COLUMN cloat_part TO cloth_part;
ALTER TABLE cloth RENAME COLUMN brand TO cloth_brand;
ALTER TABLE cloth RENAME COLUMN price TO cloth_price;

ALTER TABLE cloth ADD(
    cloth_size varchar2(6),
    cloth_id number
);

desc cloth;

ALTER TABLE cloth ADD CONSTRAINT cloth_id_pk PRIMARY KEY(cloth_id);

INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('T-Shirt', 'Nike', 29900, 'M', 1);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Jeans', 'Levis', 79000, 'L', 2);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Jacket', 'The North Face', 159000, 'XL', 3);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Sneakers', 'Adidas', 99000, '270', 4);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Hat', 'New Era', 35000, 'Free', 5);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Sweater', 'Uniqlo', 49900, 'S', 6);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Skirt', 'Zara', 45900, 'M', 7);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Coat', 'H' || CHR(38) || 'M', 119000, 'L', 8);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Shorts', 'Reebok', 39900, 'M', 9);
INSERT INTO CLOTH (CLOTH_PART, CLOTH_BRAND, CLOTH_PRICE, CLOTH_SIZE, CLOTH_ID) VALUES ('Dress', 'GU', 65900, 'S', 10);

select * from cloth order by cloth_id asc;

CREATE SEQUENCE cloth_seq 
    START WITH 11 
    INCREMENT BY 1 
    MINVALUE 1
    MAXVALUE 9999
    NOCACHE NOCYCLE;

commit;
DROP SEQUENCE cloth_seq;

cloth_seq.nextval;
