CREATE TABLE BULLETIN_BOARD_SYSTEM 
(
  BBS_ID NUMBER NOT NULL 
, BBS_NUMBER NUMBER NOT NULL 
, BBS_SUBJECT VARCHAR2(100) 
, BBS_REGIST_DATE DATE 
, BBS_RESERVATION_DATE DATE 
, BBS_CONTENT VARCHAR2(2000) 
, BBS_KEYWORD VARCHAR2(20) 
, CONSTRAINT BULLETIN_BOARD_SYSTEM_PK PRIMARY KEY 
  (
    BBS_ID 
  )
);
